#!/usr/bin/env python3
"""Apply the shared Ernos Labs navigation and footer to every page shell."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

NAV = '''  <!-- NAV: generated by tools/apply_site_shell.py -->
  <a class="skip-link" href="#view">Skip to content</a>
  <nav class="nav" aria-label="Primary navigation">
    <div class="wrap nav__in">
      <a class="brand" href="index.html" aria-label="Ernos Labs home"><svg class="mark" viewBox="0 0 26 26" width="26" height="26" aria-hidden="true"><defs><linearGradient id="ern-brand-gradient" x1="0" y1="1" x2="1" y2="0"><stop offset="0%" stop-color="#55d9b5"/><stop offset="100%" stop-color="#9da7c7"/></linearGradient></defs><path d="M13 24c0-7-4-11-4-15C9 5.5 11 3 13 2c2 1 4 3.5 4 7 0 4-4 8-4 15z" fill="url(#ern-brand-gradient)" opacity=".96"/><path d="M13 24c0-6 3-9.5 5.5-11.5M13 24c0-6-3-9.5-5.5-11.5" fill="none" stroke="#55d9b5" stroke-width="1.1" stroke-linecap="round" opacity=".5"/></svg><span>Ernos Labs</span></a>
      <div class="navplayer" id="navplayer">
        <button class="navplayer__btn" id="np-toggle" type="button" aria-label="Play or pause read-aloud">▶</button>
        <div class="navplayer__bar" aria-hidden="true"><div class="navplayer__fill" id="np-fill"></div></div>
        <span class="navplayer__status" id="np-status" aria-live="polite">Listen</span>
      </div>
      <button class="nav__burger" id="burger" type="button" aria-label="Menu">Menu</button>
      <div class="nav__links" id="navlinks">
        <span class="nav__mobile-label">Explore Ernos Labs</span>
        <div class="nav__drop nav__drop--mega" id="nav-work">
          <button class="nav__drop-btn" id="nav-work-btn" type="button" aria-haspopup="true" aria-label="Work">Work</button>
          <div class="nav__drop-menu nav__mega">
            <div class="nav__mega-col">
              <h4>Theory</h4>
              <a href="smithian-fold-theory-of-everything.html">Smithian Fold Theory</a>
              <a href="knowledge-tree.html">Knowledge Tree</a>
              <a href="smithian-fold-theory-of-everything.html#verification">How verification works</a>
            </div>
            <div class="nav__mega-col">
              <h4>Projects</h4>
              <a href="ernosplain.html">ErnosPlain</a>
              <a href="ernosdecent.html">ErnosDecent</a>
              <a href="ern-os.html">ern-OS</a>
              <a href="unisonai.html">UnisonAI</a>
            </div>
            <div class="nav__mega-col">
              <h4>Engines</h4>
              <a href="foldbot-chess.html">FoldBot Chess</a>
              <a href="fold-go.html">Fold-Go</a>
              <a href="fold-protein.html">Fold-Protein</a>
            </div>
            <div class="nav__mega-col">
              <h4>Preservation</h4>
              <a href="civ-seed.html">Civ-Seed</a>
              <a href="seed.html">Seed Vault</a>
              <a href="ai.html">AI Archive</a>
            </div>
            <a class="nav__mega-all" href="projects.html">View every project and download</a>
          </div>
        </div>
        <a href="papers.html">Publications</a>
        <a href="library.html">Library</a>
        <a href="community.html">Community</a>
        <a href="about.html">About</a>
      </div>
    </div>
  </nav>'''

FOOTER = '''  <footer class="foot">
    <div class="wrap foot__in">
      <div class="foot__about">
        <a class="brand" href="index.html"><span class="foot__mark" aria-hidden="true">◆</span><span>Ernos Labs</span></a>
        <p>Open tools, public science and long-term knowledge built by Maria Smith.</p>
        <p class="foot__snapshot"><a href="smithian-fold-theory-of-everything.html#model-status">View the current scientific record</a></p>
      </div>
      <div class="foot__cols">
        <div class="foot__col"><h4>Explore</h4><a href="smithian-fold-theory-of-everything.html">Smithian Fold Theory</a><a href="knowledge-tree.html">Knowledge Tree</a><a href="papers.html">Publications</a><a href="projects.html">Projects</a></div>
        <div class="foot__col"><h4>Ernos Labs</h4><a href="library.html">Library</a><a href="videos.html">Videos</a><a href="community.html">Community</a><a href="about.html">About</a></div>
        <div class="foot__col"><h4>Source</h4><a href="https://github.com/MettaMazza/ernos-labs-sft-platform">SFT platform ↗</a><a href="https://github.com/MettaMazza?tab=repositories">All repositories ↗</a><a href="https://discord.gg/NTAf8hnWKT">Discord ↗</a></div>
      </div>
    </div>
    <div class="wrap foot__base"><span>© <span id="year"></span> Maria Smith</span><span>Built openly in ErnosPlain.</span></div>
  </footer>'''


def replace_once(text: str, pattern: str, replacement: str, label: str, path: Path) -> str:
    updated, count = re.subn(pattern, replacement, text, count=1, flags=re.DOTALL)
    if count != 1:
        raise RuntimeError(f"Could not replace {label} exactly once in {path.name}")
    return updated


def main() -> None:
    changed = []
    for path in sorted(ROOT.glob("*.html")):
        text = path.read_text(encoding="utf-8")
        if '<nav class="nav"' not in text:
            continue
        updated = replace_once(
            text,
            r"\s*(?:<!-- NAV(?:: generated by tools/apply_site_shell\.py)? -->\s*)?(?:<a class=\"skip-link\"[^>]*>.*?</a>\s*)?<nav class=\"nav\".*?</nav>",
            "\n" + NAV,
            "navigation",
            path,
        )
        if '<footer class="foot"' in updated:
            updated = replace_once(
                updated,
                r"\s*<footer class=\"foot\".*?</footer>",
                "\n" + FOOTER,
                "footer",
                path,
            )
        canonical_url = "https://ernoslabs.com/" if path.name == "index.html" else f"https://ernoslabs.com/{path.name}"
        canonical = f'<link rel="canonical" href="{canonical_url}">'
        if re.search(r'<link\s+rel="canonical"\s+href="[^"]+"\s*/?>', updated):
            updated = re.sub(
                r'<link\s+rel="canonical"\s+href="[^"]+"\s*/?>',
                canonical,
                updated,
                count=1,
            )
        else:
            description = re.search(r'<meta\s+name="description"\s+content="[^"]*"\s*/?>', updated)
            if description:
                insert_at = description.end()
                updated = updated[:insert_at] + "\n  " + canonical + updated[insert_at:]
            else:
                title_end = updated.find("</title>")
                if title_end >= 0:
                    insert_at = title_end + len("</title>")
                    updated = updated[:insert_at] + "\n  " + canonical + updated[insert_at:]
        if updated != text:
            path.write_text(updated, encoding="utf-8")
            changed.append(path.name)
    print(f"Applied the shared site shell to {len(changed)} pages: {', '.join(changed)}")


if __name__ == "__main__":
    main()
